### ISSUE TITLE
Poor results when using pretrained model in sparse view setting

### ISSUE THREAD

**Issue by YaoanGao** [aipixel/GPS-Gaussian#41]
Hello, thanks for your wonderful work.

We employ the pretrained model offered in BaiduNetDisk **without finetuning** to predict in a sparse view setting (67.5°).
Input views:
![0](https://github.com/aipixel/GPS-Gaussian/assets/67897344/44c9899c-a1a6-41c6-a708-cd18408e5bc5)
![1](https://github.com/aipixel/GPS-Gaussian/assets/67897344/4fdd14bf-9732-4774-933f-1986d95f5930)

Interpolated target view
![0000_000_novel00](https://github.com/aipixel/GPS-Gaussian/assets/67897344/7dc4ba8a-81d1-48b0-8ef1-c572a2eac361)
The results are much worse than the sparse view experiment shown in the paper. 
The problem is similar to #32 where Gaussian regression network fails to learn how to combine the Gaussian from the left/right views.

It seems that the pretrained model cannot be used directly in sparse settings. 
If so, will finetuing on sparse view datasets alleviate the problem?

Thanks for your time!

**Comment by YaoanGao** [comment]
This issue is also related to #13 and #35 

> We use the model trained under 8-camera setup to perform inference on a 6-camera setup.

Could you possibly provide the pretrained model under 8 camera settings, which you mentioned in Table 2. in the paper?
Thanks for your help

**Comment by ShunyuanZheng** [comment]
Hi, thanks for your interest.

The pretrained model is trained for the 22.5° setup, which is significantly different from the targeting sparse view. The sparse view experiment in our paper uses the model trained on 45° synthetic data. The model can not generalize well to such an obvious domain gap if not trained on synthetic data with an augmented camera setting (e.g. from 22.5°-60°). However, the problem is not similar to #32, since the head data have a fixed topology which makes GPS-Gaussian tolerate a much wider baseline. The unreasonable results in #32 are caused by some bugs.

I think a model trained on your targeting camera setup will have a better performance. However, in a sparse-view camera setup, the FoV and the scans should be carefully adjusted to ensure the completeness of human body after rectification. For example, the scans with significant torso movements should be resized smaller. Also, I think a baseline larger than 60° is difficult for GPS-Gaussian, even trained on elaborate data. Too many restrictions exist due to the binocular depth estimation.

**Comment by ShunyuanZheng** [comment]
> This issue is also related to #13 and #35
> 
> > We use the model trained under 8-camera setup to perform inference on a 6-camera setup.
> 
> Could you possibly provide the pretrained model under 8 camera settings, which you mentioned in Table 2. in the paper? Thanks for your help

Sorry, I rarely used the model under 8 camera setup after conducting the experiments for the paper, and the code is slightly different from the open-source version. You can synthesize the training data and re-implement it.

**Comment by YaoanGao** [comment]
I see. Thanks for the quick reply.
