### ISSUE TITLE
Twindom Dataset and Loader

### ISSUE THREAD

**Issue by johnnylu305** [aipixel/GPS-Gaussian#57]
Hi, thank you for the great work. I want to reproduce the results with Twindom dataset on GPS-Gaussian and E-NeRF. However, I am not too familiar with this dataset and cannot find the download page for it.

1. Can you guide me to access the dataset?
2. It will be great if you can share the Twindom data loader for GPS-Gaussian and E-NeRF.

Thanks

**Comment by ShunyuanZheng** [comment]
Hi, thanks for your interest.

The Twindom dataset is not an open-source dataset, you can purchase the license on their homepage. However, since Twindom shares the same data format as THuman2.0, the dataloader for GPS-Gaussian is the same as the one for THuman2.0.

Further, here is the dataloader and config file of THuman2.0 for ENeRF, I referred to the dataloader for DTU in lib/datasets/dtu/enerf.py. The data is structured as in GPS-Gaussian.
[ENeRF_dataloader_for_THuman.zip](https://github.com/user-attachments/files/16510421/ENeRF_dataloader_for_THuman.zip)

**Comment by johnnylu305** [comment]
Got it. Thanks for the quick response.

**Comment by johnnylu305** [comment]
I contact Twindom. Unfortunately, they no longer sell the data. :(
