### ISSUE TITLE
Experiments on the 3DGS

### ISSUE THREAD

**Issue by JuntingLee** [aipixel/GPS-Gaussian#62]
Hi, 
Congratualtion for your work!

I am trying to test the result of 3DGS under different input views. As the  shared code has input of 16 views, do you think 3DGS will also benefit from more inputs when compared with GPS-GS. 

When I tested some val samples in 3dgs, I found some ones such `0000` can not get valid result during the matching process of the colmap.  I think it may be due to almost textureless clothes in these samples. 
In addition, for some samples that can succsesfully get camera parameter from colmap, I found the intrinsic parameter is a little bit diferent from the orginal image size `1024*1024`.

I think you can directly use the camera parameter from your rendering code to train 3DGS per scene, so that you will not meet the two issue mentioned above. It would be appreciated if you could share the dataloader for 3DGS.

Looking forward to your reply~

**Comment by ShunyuanZheng** [comment]
Hi, thanks for your interest.

I think 16 camera views are still too sparse for original 3DGS.

On our synthetic data, you can use real camera parameters rather than those estimated from COLMAP. Maybe 16 cameras is also challenging for COLMAP, especially on textureless clothes.

You can try our modified 3D-GS code[static_3dgs_batch.zip](https://github.com/user-attachments/files/16974179/static_3dgs_batch.zip). However, I think the data should be reorganized as the example data
[example_data.zip](https://github.com/user-attachments/files/16974196/example_data.zip). I have not used this code for a long time, so there may be some bugs on the reading file path. You can build a 3DGS model for each static human or each frame by running run_bash.sh.

[static_3dgs_batch.zip](https://github.com/user-attachments/files/16974179/static_3dgs_batch.zip)

**Comment by JuntingLee** [comment]
> Hi, thanks for your interest.
> 
> I think 16 camera views are still too sparse for original 3DGS.
> 
> On our synthetic data, you can use real camera parameters rather than those estimated from COLMAP. Maybe 16 cameras is also challenging for COLMAP, especially on textureless clothes.
> 
> You can try our modified 3D-GS code [static_3dgs_batch.zip](https://github.com/user-attachments/files/16974179/static_3dgs_batch.zip). However, I think the data should be reorganized as the example data [example_data.zip](https://github.com/user-attachments/files/16974196/example_data.zip). I have not used this code for a long time, so there may be some bugs on the reading file path. You can build a 3DGS model for each static human or each frame by running run_bash.sh.

Hi, Shunyuan!

Thanks for reply so quickly!
We appreciate for your opinions and code about 3DGS! It helps a lot.

Best Regards,
Junting
